[package]
name = "dectdump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bitvec = "1.0.1"
nom = "7.1.3"

tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros", "net"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.13", features = ["codec", "net"] }
